apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h5rbfnwjo-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-53051de0b8.mpgn.p3.openshiftapps.com/rhtap/rhtap-qe:d731e72292c372c9f377e2b25930d303ef015194@sha256:955181e628c7990d7b29921ca331766f8a2d1d8b19e61ff4601b7f83f178cd6a
          name: container-image
